services:
  mysql:
    image: mysql:8.0
    command:
      - --default-authentication-plugin=mysql_native_password
      - --ssl=0
      - --sha256-password-auto-generate-rsa-keys=OFF
      - --caching-sha2-password-auto-generate-rsa-keys=OFF
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: golden_dak
      MYSQL_USER: goldendak
      MYSQL_PASSWORD: goldendak
    ports:
      - "3306:3306"
    volumes:
      - E:/docker/goldendak_mysql_data:/var/lib/mysql
